name       : sunflower
version    : 0.3.61
release    : 5
source     :
    - https://github.com/MeanEYE/Sunflower/archive/0.3-61.tar.gz : 5f8d96316b3e6c157926da5c390a26a45de97132e98e2fd70ada5b5b7fa14def
license    : GPL-3.0-or-later
component  : desktop
summary    : Sunflower FM is a Twin-panel file manager.
description: |
    Small and highly customizable twin-panel file manager for Linux. It is intended to be an easy-to-use and powerful file manager that seamlessly integrates into the GNOME desktop environment (but not limited to).
builddeps  :
    - pkgconfig(pygobject-2.0)
    - pkgconfig(librsvg-2.0)
    - desktop-file-utils
rundeps    :
    - gvfs
    - mutagen
    - python-chardet
    - python-dbus
    - python-gtk2
install    : |
    install -D -m 0755 $pkgfiles/sunflower $installdir/usr/bin/sunflower
    install -d -m 0644 $installdir/usr/share/sunflower
    cp -r * $installdir/usr/share/sunflower
    install -Dm644 Sunflower.desktop $installdir/usr/share/applications/sunflower.desktop
    install -Dm644 images/sunflower_64.png $installdir/usr/share/pixmaps/sunflower.png
